The file spilt didn’t work so I’ve sysmlinked the rc file from here.

diff --git a/zsh.d/zshPS02 b/zsh.d/zshPS02
--- a/zsh.d/zshPS02
+++ b/zsh.d/zshPS02
@@ -2,11 +2,13 @@
 returnValue=$1;
 
 function textErrorFunction() {
-	echo "%{${whiteOnRed}%}${UL}Error ${LU}%{${RESET}%}%{${redOnWhite}%}${UL} $1 %{$LU$RESET%}";
+	echo "%{${whiteOnRed}%}${UL}Error ${LU}%{${RESET}%}%{${redOnWhite}%}${UL} $returnValue %{${LU}${RESET}%}";
 }
 
 function returnPrompt()	{
-	echo $( [[ "$returnValue" != 0 ]] && echo textErrorFunction $returnValue || echo $textPath ) $textShellPink"\:> ";
+	local _textPath=$([[ "$PWD" = "/Users/stephen-harold" ]] && echo "%{${WHITE}%}('${home}%{${WHITE}%}')%{${RESET}%}" || echo "%{${WHITE}%}(%2~%{${CYAN}%}/%{${WHITE}%})%{${RESET}%}");
+	local _textShellPink=$( echo "%{${PINK}%}${SHELL//*\/}%{${RESET}%}" );
+	return $( [[ "${returnValue}" != 0 ]] && echo textErrorFunction $returnValue || echo $_textPath ) $_textShellPink"\:> ";
 }
 
-returnPrompt;
+echo returnPrompt;
diff --git a/zsh.d/zshProfile b/zsh.d/zshProfile
--- a/zsh.d/zshProfile
+++ b/zsh.d/zshProfile
@@ -1,31 +1,28 @@
 #!/bin/zsh
-declare -A arrayProfiles;
+# declaration debug function and export
+declare -f DEBUG;
+export DEBUG=1; # SET TO 1 FOR ON
 
-# -= DOCK: HIDE/UNHIDE =-
-defaults write com.apple.dock autohide-delay -float 0.0001; killall Dock;
-
-# -= FILES: SOURCE PROFILE FILES =-
-function sourceProfile() {
-	arrayProfiles=( \
-	['1']="/Users/stephen-harold/.local/profiles/zsh.d/zshOptions" \
-	['2']="/Users/stephen-harold/.local/profiles/common.d/commonConfig" \
-	['3']="/Users/stephen-harold/.local/profiles/common.d/commonExports" \
-	['4']="/Users/stephen-harold/.local/profiles/zsh.d/zshExports" \
-	['5']="/Users/stephen-harold/.local/profiles/common.d/commonAilieses" \
-	['6']="/Users/stephen-harold/.local/profiles/zsh.d/zshAlieses" \
-	['7']="/Users/stephen-harold/.local/profiles/common.d/commonOverides" \
-	['8']="/Users/stephen-harold/.local/profiles/zsh.d/zshOverides" \
-	['9']="/Users/stephen-harold/.local/profiles/common.d/commonPeriodics" );
-
-	for number in {1..9}
-	do
-		local thisFile=${arrayProfiles[$number]};
-		[[ -r $thisFile ]] && source $thisFile || echo "\e[1;31mFile not found:\e[1;37m $thisFile \e[m"
-		. Dbug "$index. Called source on $thisFile.";
-	done
-	. Dbug "Called source on all ${arrayProfiles[#]} files in total.";
+function DEBUG() {
+	local scriptName=$1;
+	local message=$2;
+	[[ "$DEBUG" = 1 ]] && echo "${WHITE}-${RED}-=|] $(date +%H:%M:%S) [|=-${WHITE}-${YELLOW}-=|] ${WHITE}{scriptName:-"Not Set!"} [|=-${WHITE}-${GREEN}-=|] ${message:-"Message Variable Not Set. [|=-${WHITE}-"}${RESET}";
 }
 
-. Dbug "zsh profile ignition";
-sourceProfile;
-unset -f sourceProfile;
+declare -A arrayProfiles=(
+	['0']="/Users/stephen-harold/.local/profiles/common.d/commonExports"
+	['1']="/Users/stephen-harold/.local/profiles/common.d/commonConfig"
+	['2']="/Users/stephen-harold/.local/profiles/common.d/commonAilieses"
+	['3']="/Users/stephen-harold/.local/profiles/common.d/commonOverides"
+	['4']="/Users/stephen-harold/.local/profiles/common.d/commonPeriodics"
+	['5']="/Users/stephen-harold/.local/profiles/zshProfiles/zshOptions"
+	['6']="/Users/stephen-harold/.local/profiles/zshProfiles/zshExports"
+	['7']="/Users/stephen-harold/.local/profiles/zshProfiles/zshAlieses"
+	['8']="/Users/stephen-harold/.local/profiles/zshProfiles/zshOverides" );
+
+for _num in {0..8}
+do
+	_thisFile=${arrayProfiles[$_num]};
+	[[ -r "$_thisFile" ]] && DEBUG "zshProfile" "$_num. Calling source on ${WHITE}  "$_thisFile" ${RESET}."; source "$_thisFile" || echo "zshProfile" "$_num. ${RED}File not found:${WHITE} "$_thisFile" ${RESET}"
+done
+DEBUG "zshProfile" "Called source on all "${#arrayProfiles[*]}" files in total.";
